2025-04-06 20:26:08,787 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\connection.json
2025-04-06 20:26:08,787 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\configuration.json
2025-04-06 20:26:08,788 - root - CRITICAL - Application failed: name 'DatabaseConnect' is not defined
Traceback (most recent call last):
  File "C:\python_projects\ConvertertBSDUplo\convertor\main.py", line 20, in main
    service = DataProcessingService(config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python_projects\ConvertertBSDUplo\convertor\app\services\data_service.py", line 14, in __init__
    self._init_components()
  File "C:\python_projects\ConvertertBSDUplo\convertor\app\services\data_service.py", line 34, in _init_components
    self.db = DatabaseConnect(
              ^^^^^^^^^^^^^^^
NameError: name 'DatabaseConnect' is not defined
2025-04-06 21:20:15,211 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\connection.json
2025-04-06 21:20:15,212 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\configuration.json
2025-04-06 21:20:15,330 - convertor.app.core.database - INFO - Успешное подключение к PostgreSQL
2025-04-06 21:20:15,330 - convertor.app.core.database - INFO - 2025-02-1 12:00:00
2025-04-06 21:20:15,330 - convertor.app.core.database - INFO - Используется start_date: 2025-02-1 12:00:00
2025-04-06 21:20:15,355 - convertor.app.core.database - INFO - Найдено нарушений: 1
2025-04-06 21:20:15,355 - convertor.app.services.data_service - INFO - Found 1 new violations
2025-04-06 21:20:15,420 - convertor.app.core.ftp_client - INFO - FTP подключение установлено
2025-04-06 21:20:15,770 - convertor.app.core.ftp_client - INFO - Загружен файл 2309033_2025_02_11_10_07_38_13_04_00.jpg (121840 байт)
2025-04-06 21:20:15,839 - convertor.app.services.api_service - ERROR - Server error 400: Bad Request
Status: 400
Headers: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 06 Apr 2025 18:20:15 GMT', 'Connection': 'close'}
Body: {
  "timestamp": "2025-04-06T18:20:15.865+00:00",
  "status": 400,
  "error": "Bad Request",
  "path": "/send"
}
2025-04-06 21:20:15,840 - convertor.app.core.database - INFO - Соединение с PostgreSQL закрыто
2025-04-06 21:20:15,852 - convertor.app.core.ftp_client - INFO - FTP соединение закрыто
2025-04-06 21:26:46,710 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\connection.json
2025-04-06 21:26:46,711 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\configuration.json
2025-04-06 21:26:46,832 - convertor.app.core.database - INFO - Успешное подключение к PostgreSQL
2025-04-06 21:26:46,832 - convertor.app.core.database - INFO - 2025-02-1 12:00:00
2025-04-06 21:26:46,833 - convertor.app.core.database - INFO - Используется start_date: 2025-02-1 12:00:00
2025-04-06 21:26:46,869 - convertor.app.core.database - INFO - Найдено нарушений: 1
2025-04-06 21:26:46,869 - convertor.app.services.data_service - INFO - Found 1 new violations
2025-04-06 21:26:46,951 - convertor.app.core.ftp_client - INFO - FTP подключение установлено
2025-04-06 21:26:47,263 - convertor.app.core.ftp_client - INFO - Загружен файл 2309033_2025_02_11_10_07_38_13_04_00.jpg (121840 байт)
2025-04-06 21:26:47,498 - convertor.app.services.api_service - ERROR - Server error 400: Bad Request
Status: 400
Headers: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 06 Apr 2025 18:26:47 GMT', 'Connection': 'close'}
Body: {
  "timestamp": "2025-04-06T18:26:47.508+00:00",
  "status": 400,
  "error": "Bad Request",
  "path": "/send"
}
2025-04-06 21:26:47,498 - convertor.app.core.database - INFO - Соединение с PostgreSQL закрыто
2025-04-06 21:26:47,512 - convertor.app.core.ftp_client - INFO - FTP соединение закрыто
2025-04-06 21:27:45,177 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\connection.json
2025-04-06 21:27:45,177 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\configuration.json
2025-04-06 21:27:45,315 - convertor.app.core.database - INFO - Успешное подключение к PostgreSQL
2025-04-06 21:27:45,315 - convertor.app.core.database - INFO - 2025-02-1 12:00:00
2025-04-06 21:27:45,315 - convertor.app.core.database - INFO - Используется start_date: 2025-02-1 12:00:00
2025-04-06 21:27:45,354 - convertor.app.core.database - INFO - Найдено нарушений: 1
2025-04-06 21:27:45,354 - convertor.app.services.data_service - INFO - Found 1 new violations
2025-04-06 21:27:45,661 - convertor.app.core.ftp_client - INFO - FTP подключение установлено
2025-04-06 21:27:46,228 - convertor.app.core.ftp_client - INFO - Загружен файл 2309033_2025_02_11_10_07_38_13_04_00.jpg (121840 байт)
2025-04-06 21:27:46,870 - convertor.app.services.api_service - ERROR - Server error 400: Bad Request
Status: 400
Headers: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 06 Apr 2025 18:27:46 GMT', 'Connection': 'close'}
Body: {
  "timestamp": "2025-04-06T18:27:46.801+00:00",
  "status": 400,
  "error": "Bad Request",
  "path": "/send"
}
2025-04-06 21:27:46,870 - convertor.app.core.database - INFO - Соединение с PostgreSQL закрыто
2025-04-06 21:27:46,890 - convertor.app.core.ftp_client - INFO - FTP соединение закрыто
2025-04-06 21:40:49,549 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\connection.json
2025-04-06 21:40:49,550 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\configuration.json
2025-04-06 21:40:49,650 - convertor.app.core.database - INFO - Успешное подключение к PostgreSQL
2025-04-06 21:40:49,650 - convertor.app.core.database - INFO - 2025-02-1 12:00:00
2025-04-06 21:40:49,650 - convertor.app.core.database - INFO - Используется start_date: 2025-02-1 12:00:00
2025-04-06 21:40:49,680 - convertor.app.core.database - INFO - Найдено нарушений: 1
2025-04-06 21:40:49,681 - convertor.app.services.data_service - INFO - Found 1 new violations
2025-04-06 21:40:49,744 - convertor.app.core.ftp_client - INFO - FTP подключение установлено
2025-04-06 21:40:49,943 - convertor.app.core.ftp_client - INFO - Загружен файл 2309033_2025_02_11_10_07_38_13_04_00.jpg (121840 байт)
2025-04-06 21:41:05,400 - convertor.app.services.api_service - ERROR - Request failed: HTTPConnectionPool(host='172.21.36.63', port=8080): Max retries exceeded with url: /send (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022E2A1DFDD0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-04-06 21:41:05,400 - convertor.app.core.database - INFO - Соединение с PostgreSQL закрыто
2025-04-06 21:41:05,454 - convertor.app.core.ftp_client - INFO - FTP соединение закрыто
2025-04-06 21:42:03,252 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\connection.json
2025-04-06 21:42:03,252 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\configuration.json
2025-04-06 21:42:03,369 - convertor.app.core.database - INFO - Успешное подключение к PostgreSQL
2025-04-06 21:42:03,369 - convertor.app.core.database - INFO - 2025-02-1 12:00:00
2025-04-06 21:42:03,370 - convertor.app.core.database - INFO - Используется start_date: 2025-02-1 12:00:00
2025-04-06 21:42:03,409 - convertor.app.core.database - INFO - Найдено нарушений: 1
2025-04-06 21:42:03,410 - convertor.app.services.data_service - INFO - Found 1 new violations
2025-04-06 21:42:03,486 - convertor.app.core.ftp_client - INFO - FTP подключение установлено
2025-04-06 21:42:03,760 - convertor.app.core.ftp_client - INFO - Загружен файл 2309033_2025_02_11_10_07_38_13_04_00.jpg (121840 байт)
2025-04-06 21:42:04,343 - convertor.app.services.api_service - ERROR - Server error 400: Bad Request
Status: 400
Headers: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 06 Apr 2025 18:42:04 GMT', 'Connection': 'close'}
Body: {
  "timestamp": "2025-04-06T18:42:04.294+00:00",
  "status": 400,
  "error": "Bad Request",
  "path": "/send"
}
2025-04-06 21:42:04,344 - convertor.app.core.database - INFO - Соединение с PostgreSQL закрыто
2025-04-06 21:42:04,353 - convertor.app.core.ftp_client - INFO - FTP соединение закрыто
2025-04-06 21:54:08,448 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\connection.json
2025-04-06 21:54:08,449 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\configuration.json
2025-04-06 21:54:08,638 - convertor.app.core.database - INFO - Успешное подключение к PostgreSQL
2025-04-06 21:54:08,638 - convertor.app.core.database - INFO - 2025-02-1 12:00:00
2025-04-06 21:54:08,639 - convertor.app.core.database - INFO - Используется start_date: 2025-02-1 12:00:00
2025-04-06 21:54:08,663 - convertor.app.core.database - INFO - Найдено нарушений: 1
2025-04-06 21:54:08,663 - convertor.app.services.data_service - INFO - Found 1 new violations
2025-04-06 21:54:08,736 - convertor.app.core.ftp_client - INFO - FTP подключение установлено
2025-04-06 21:54:09,060 - convertor.app.core.ftp_client - INFO - Загружен файл 2309033_2025_02_11_10_07_38_13_04_00.jpg (121840 байт)
2025-04-06 21:54:09,151 - convertor.app.services.api_service - ERROR - Server error 400: Bad Request
Status: 400
Headers: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 06 Apr 2025 18:54:09 GMT', 'Connection': 'close'}
Body: {
  "timestamp": "2025-04-06T18:54:09.436+00:00",
  "status": 400,
  "error": "Bad Request",
  "path": "/send"
}
2025-04-06 21:54:09,151 - convertor.app.core.database - INFO - Соединение с PostgreSQL закрыто
2025-04-06 21:54:09,203 - convertor.app.core.ftp_client - INFO - FTP соединение закрыто
2025-04-06 21:56:07,582 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\connection.json
2025-04-06 21:56:07,583 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\configuration.json
2025-04-06 21:56:07,689 - convertor.app.core.database - INFO - Успешное подключение к PostgreSQL
2025-04-06 21:56:07,689 - convertor.app.core.database - INFO - 2025-02-1 12:00:00
2025-04-06 21:56:07,690 - convertor.app.core.database - INFO - Используется start_date: 2025-02-1 12:00:00
2025-04-06 21:56:07,726 - convertor.app.core.database - INFO - Найдено нарушений: 1
2025-04-06 21:56:07,726 - convertor.app.services.data_service - INFO - Found 1 new violations
2025-04-06 21:56:07,792 - convertor.app.core.ftp_client - INFO - FTP подключение установлено
2025-04-06 21:56:08,104 - convertor.app.core.ftp_client - INFO - Загружен файл 2309033_2025_02_11_10_07_38_13_04_00.jpg (121840 байт)
2025-04-06 21:56:08,111 - convertor.app.services.data_service - ERROR - Failed to process violation 144528: 'DataProcessingService' object has no attribute '_enrich_data'
2025-04-06 21:56:08,112 - convertor.app.core.database - INFO - Соединение с PostgreSQL закрыто
2025-04-06 21:56:08,122 - convertor.app.core.ftp_client - INFO - FTP соединение закрыто
2025-04-06 21:56:20,662 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\connection.json
2025-04-06 21:56:20,663 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\configuration.json
2025-04-06 21:56:20,759 - convertor.app.core.database - INFO - Успешное подключение к PostgreSQL
2025-04-06 21:56:20,760 - convertor.app.core.database - INFO - 2025-02-1 12:00:00
2025-04-06 21:56:20,761 - convertor.app.core.database - INFO - Используется start_date: 2025-02-1 12:00:00
2025-04-06 21:56:20,795 - convertor.app.core.database - INFO - Найдено нарушений: 1
2025-04-06 21:56:20,795 - convertor.app.services.data_service - INFO - Found 1 new violations
2025-04-06 21:56:20,857 - convertor.app.core.ftp_client - INFO - FTP подключение установлено
2025-04-06 21:56:21,369 - convertor.app.core.ftp_client - INFO - Загружен файл 2309033_2025_02_11_10_07_38_13_04_00.jpg (121840 байт)
2025-04-06 21:56:21,428 - convertor.app.services.api_service - ERROR - Server error 400: Bad Request
Status: 400
Headers: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 06 Apr 2025 18:56:20 GMT', 'Connection': 'close'}
Body: {
  "timestamp": "2025-04-06T18:56:20.835+00:00",
  "status": 400,
  "error": "Bad Request",
  "path": "/send"
}
2025-04-06 21:56:21,428 - convertor.app.core.database - INFO - Соединение с PostgreSQL закрыто
2025-04-06 21:56:21,449 - convertor.app.core.ftp_client - INFO - FTP соединение закрыто
2025-04-06 21:56:36,748 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\connection.json
2025-04-06 21:56:36,748 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\configuration.json
2025-04-06 21:56:36,869 - convertor.app.core.database - INFO - Успешное подключение к PostgreSQL
2025-04-06 21:56:36,869 - convertor.app.core.database - INFO - 2025-02-1 12:00:00
2025-04-06 21:56:36,870 - convertor.app.core.database - INFO - Используется start_date: 2025-02-1 12:00:00
2025-04-06 21:56:36,945 - convertor.app.core.database - INFO - Найдено нарушений: 1
2025-04-06 21:56:36,945 - convertor.app.services.data_service - INFO - Found 1 new violations
2025-04-06 21:56:37,063 - convertor.app.core.ftp_client - INFO - FTP подключение установлено
2025-04-06 21:56:37,381 - convertor.app.core.ftp_client - INFO - Загружен файл 2309033_2025_02_11_10_07_38_13_04_00.jpg (121840 байт)
2025-04-06 21:56:37,450 - convertor.app.services.api_service - ERROR - Server error 400: Bad Request
Status: 400
Headers: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 06 Apr 2025 18:56:37 GMT', 'Connection': 'close'}
Body: {
  "timestamp": "2025-04-06T18:56:37.488+00:00",
  "status": 400,
  "error": "Bad Request",
  "path": "/send"
}
2025-04-06 21:56:37,451 - convertor.app.core.database - INFO - Соединение с PostgreSQL закрыто
2025-04-06 21:56:37,461 - convertor.app.core.ftp_client - INFO - FTP соединение закрыто
2025-04-06 21:57:02,823 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\connection.json
2025-04-06 21:57:02,823 - convertor.app.utils.config_loader - INFO - Успешно загружен C:\python_projects\ConvertertBSDUplo\convertor\conf\configuration.json
2025-04-06 21:57:02,991 - convertor.app.core.database - INFO - Успешное подключение к PostgreSQL
2025-04-06 21:57:02,992 - convertor.app.core.database - INFO - 2025-02-1 12:00:00
2025-04-06 21:57:02,992 - convertor.app.core.database - INFO - Используется start_date: 2025-02-1 12:00:00
2025-04-06 21:57:03,029 - convertor.app.core.database - INFO - Найдено нарушений: 1
2025-04-06 21:57:03,029 - convertor.app.services.data_service - INFO - Found 1 new violations
2025-04-06 21:57:03,098 - convertor.app.core.ftp_client - INFO - FTP подключение установлено
2025-04-06 21:57:03,406 - convertor.app.core.ftp_client - INFO - Загружен файл 2309033_2025_02_11_10_07_38_13_04_00.jpg (121840 байт)
2025-04-06 21:57:03,515 - convertor.app.services.api_service - ERROR - Server error 400: Bad Request
Status: 400
Headers: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 06 Apr 2025 18:57:03 GMT', 'Connection': 'close'}
Body: {
  "timestamp": "2025-04-06T18:57:03.392+00:00",
  "status": 400,
  "error": "Bad Request",
  "path": "/send"
}
2025-04-06 21:57:03,515 - convertor.app.core.database - INFO - Соединение с PostgreSQL закрыто
2025-04-06 21:57:03,529 - convertor.app.core.ftp_client - INFO - FTP соединение закрыто
